# Настройки генератора руды
[ore_generator]

# Максимальная вместимость FE
energy_capacity = 1000000

# Сколько FE потребляется за тик за каждую руду
energy_per_tick = 10000

# Сколько тиков нужно для генерации одной руды
ticks_per_ore = 1

# Сколько руд генерируется за один тик
ores_per_tick = 32

# Дополнительные руды, которые не имеют тега forge:ores
custom_ores = [
    "minecraft:iron_ore",
    "minecraft:gold_ore"
]
