modLoader = "javafml"
loaderVersion = "[@FORGE_LOADER_MAJOR@,)"
license = "MIT"

[[mods]]
modId = "linden"
logoFile = "icon.png"
version = "${version}"
displayName = "Linden"
description = '''
Edge for TechnoRPG <3
'''




[[dependencies.linden]]
modId = "forge"
mandatory = true
versionRange = "[@FORGE_LOADER_MAJOR@,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.linden]]
modId = "minecraft"
mandatory = true
versionRange = "[@MINECRAFT@,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.linden]]
modId = "botania"
mandatory = true
versionRange = "[1.20.1-448-FORGE,)"
ordering = "NONE"
side = "BOTH"
